config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/about'
  root 'home#index'

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_nav.html.erb
<%= link_to "HOME", root_path%> |
<%= link_to "About my APP", home_about_path%>

app/views/home/about.html.erb
<h1>Hello</h1>
<p>This is ABOUT!!</p>

app/views/home/index.html.erb
<h1>Hello</h1>
<p>You're in stock ;) </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MY MY MY!! Stocking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <p>Hello World!</p>
<%= render 'home/nav'%>
<div class="Container">
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       
    <%= yield %>
    </div>
  </body>
</html>